### ISSUE TITLE
Add QGIS project

### ISSUE THREAD

**Issue by rbovard** [sitnyon/data-model-sdis#10]

**Comment by ponceta** [comment]
.qml files or .qlr files could be already great.

.qgs files are hard to maintain.

**Comment by ponceta** [comment]
https://github.com/opengisch/qgis_trackable_project_files 
Utiliser le plugin pour le suivi de versionnement du fichier .qgs à sa création.
Sauvegarder les accès à travers un fichier pg_config pour éviter la sauvegarde des identifiants.

**Comment by tlesage** [comment]
Merci @ponceta pour ce lien, je vais regarder. Pour les credentials, on utilise le système d'authentification avec la base `qgis-auth.db` donc pas de soucis de côté là.

**Comment by tlesage** [comment]
All "SDIS" data can now be edited using GeoMapFish. Data models and mapserver configuration on the repo have been updated
